title: Keats
email: team@keats.com
description: >-
  Keats is a learning app that teaches computer science and  mathematics in a fun and interactive way.
baseurl: ""
url: "https://keats.app"
twitter_username: keats_app
github_username:  keatsapp

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
